### ISSUE TITLE
Need support for Python 3

### ISSUE THREAD

**Issue by forest-jiang** [tdomhan/pyautoweka#4]
I have tested using 2to3 tool. Seems work.

**Comment by melissadale** [comment]
This does not work in Python 3 (Python 3.7.8). I had received `ImportError: cannot import name 'DataSet' from 'pyautoweka'` I made an environment set to Python 2.7, installed numpy, and then pyautoweka using `pip install pyautoweka`, and now it appears to work.

**Comment by mdziezyc** [comment]
Do I understand correctly - PyAutoWeka does not work on python 3 (specificity I have Anaconda 3.8.5)? I'm troubleshooting `ImportError: cannot import name 'DataSet' from partially initialized module 'pyautoweka' (most likely due to a circular import)` for half hour right now.

**Comment by melissadale** [comment]
It did not work for me until I made an environment with python 2.7. I was getting an import error about 'DataSet', but I do not recall if it was this exact error or not. Anaconda 3.8.5 is fine, but you might try using it to make an environment with a Python2.7 interpreter, something like `conda create --name wekaEnv python=2.7`

**Comment by mdziezyc** [comment]
Thx! I just switched to autoskleran ^^'
